### ISSUE TITLE
User.get_info always returns false

### ISSUE THREAD

**Issue by ldrbrandon** [plaid/plaid-ruby#114] opened 2016-05-16 23:14 UTC
This is probably moot at this point since v2.0 is out now but in the gem pre 2.0, but I'm still using v1.7 and I'm sure others are as well. I'm not sure how the `User.get_info` method ever worked. The 2 issues were:

1. `User.get_info` calls `User.get('info') which in turn will return false immediately unless the `User.permissions` array includes 'info'. The problem there is that when creating a user or restoring a user, it runs into this same problem where it will try and make a request to 'info/get' but obviously the permissions don't include it and therefore it will simply return false.

2. If you did somehow make it past that check `unless self.permit? auth_level` then you would be stuck trying to make the `Connection.secure_get('info', self.access_token)` The problem with this call is that the `secure_get` never includes the `client_id` or the `secret`; which per the Plaid API Docs are required in a GET request to '/info/get'

There are ways around this (some hacky-er) than others but I just thought I'd bring it up since v2.0 is out and I'm sure not everyone has upgraded just yet.

**Comment by be9** [comment] 2016-05-17 04:58
@ldrbrandon Thanks for sharing! We are going to finally release 2.0.0 in upcoming days, and the recommendation is to upgrade to it (but I'm biased here because I'm the main author of 2.0.0 😎).

Unfortunately, the `User#permissions` array and `Connection.secure_get` method don't work as intended in the old version.

**Comment by daaaveg** [comment] 2016-05-17 08:02
I'm also still on v1.7 and i'm suddenly getting `Plaid::RequestFailed (invalid credentials)` errors in my application when calling `User.get('connect')`.

Were there changes to the Plaid API that are not backwards compatible?

**Comment by michaelckelly** [comment] 2016-05-17 16:15
@daaaveg -

The `invalid credentials` error is likely because the access token for which you are trying to retrieve transactions no longer has valid credentials associated with it. This is generally because the user has changed their password. When an access token is in this state, Plaid cannot pull updated transaction data and will return an error in response to API requests to retrieve data.

You can go through the [update user][1] process to get this access token back in a good state!

If you still have questions, drop us a note at support@plaid.com with the affected access token.

> Were there changes to the Plaid API that are not backwards compatible?

There were no breaking API changes at the endpoint level - you should be able to integrate the new gem, when published, and be good to go.

[1]: https://plaid.com/docs/api/#update-connect-user

**Comment by daaaveg** [comment] 2016-05-17 17:35
@michaelckelly thanks for the clarification. I'm using Plaid for my personal accounts and everything has been running fine until a day ago when I started getting the credentials error. I haven't changed any passwords on any accounts so I was wondering if there were any changes to the Plaid API that would have broken the client in v1.7

I'll try updating the user to get a new access token and see if that fixes things.

**Comment by be9** [comment] 2016-10-19 06:38
Closing as outdated. One should be definitely using 2.x.x by now.

**Closed by be9** 2016-10-19 06:38 UTC
