### ISSUE TITLE
Doesn't work with Rails 5.2.6 and Ruby 2.7.5

### ISSUE THREAD

**Issue by noctivityinc** [plaid/plaid-ruby#399] opened 2021-12-16 22:21 UTC
The latest version of the gem won't install with Rails 5.2.6 and Ruby 2.7.5.  Is there some trick to getting this to work?

**Comment by phoenixy1** [comment] 2021-12-20 19:27
I was not able to reproduce this issue using the same version of Ruby. 

Also, per Ruby docs, Rails 5.2.6 is not compatible with Ruby 2.7.5, which may be the source of your problems: https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html 
https://github.com/rails/rails/issues/38426

**Comment by phoenixy1** [comment] 2021-12-22 18:17
Closing this issue -- if you update to a compatible version of rails and still encounter the problem, please re-open the issue and include details of the error message you encountered. Thanks!

**Closed by phoenixy1** 2021-12-22 18:17 UTC
