### ISSUE TITLE
fix: create a link in sandbox

### ISSUE THREAD

**Issue by lyna-azerouk** [plaid/plaid-ruby#506] opened 2024-11-11 13:44 UTC
#### Summary
In the ruby backend, Encountering a NameError when attempting to access `Plaid::CraCheckReportProduct` in the Plaid library.

#### Steps to reproduce:
1- set up the env file.
2- try to generate a new link for the sandbox env `post '/api/create_link_token'` 

### Proposed Solution: 
- Replace `Plaid::CraCheckReportProduct` with `Plaid::CraCheckReportBaseReportGetRequest`

## Screen 
![Screenshot 2024-11-11 at 14 39 44](https://github.com/user-attachments/assets/5eed1dae-5b92-4fa5-9c14-3ed99f88ea3a)

**Comment by phoenixy1** [comment] 2024-11-15 18:16
This appears to be caused by using the Quickstart with a different version of the Plaid ruby client library than the one specified in the Gemfile.  To prevent this this, try starting the project with `bundle exec ruby app.rb` rather than `./start.sh`. (We'll release a fix for this soon.)

**Closed by phoenixy1** 2024-11-15 18:16 UTC
